using Microsoft.AspNetCore.Mvc; using Microsoft.EntityFrameworkCore; using SdlcDashboard.Api.Data; using SdlcDashboard.Api.Models; using SdlcDashboard.Api.Infrastructure; using System.Text.RegularExpressions;
namespace SdlcDashboard.Api.Controllers;
[ApiController,Route("api")]
public class ApiController(AppDbContext db,IIssueProvider issues,ISecretStore secrets,IAnalystClient analyst):ControllerBase {
 string Tenant=>HttpContext.Items["tenant"]!.ToString()!; async Task<Workspace?> Ws(Guid id)=>await db.Workspaces.Include(x=>x.Client).SingleOrDefaultAsync(x=>x.Id==id&&x.TenantId==Tenant);
 [HttpGet("workspaces")] public async Task<IActionResult> Workspaces()=>Ok(await db.Workspaces.Where(x=>x.TenantId==Tenant).ToListAsync());
 public record WorkspaceIn(string Name,string Slug,string Platform,string PlatformRef,string SpecsPath);
 [HttpPost("workspaces")] public async Task<IActionResult> Create(WorkspaceIn i){var client=await db.Clients.FirstOrDefaultAsync(x=>x.Name==i.Name);if(client is null){client=new Client{Name=i.Name};db.Clients.Add(client);}var w=new Workspace{TenantId=Tenant,Client=client,Name=i.Name,Slug=i.Slug,Platform=i.Platform,PlatformRef=i.PlatformRef,SpecsPath=i.SpecsPath};db.Workspaces.Add(w);await db.SaveChangesAsync();return Created($"api/workspaces/{w.Id}",w);}
 [HttpPut("workspaces/{id:guid}")] public async Task<IActionResult> Update(Guid id,WorkspaceIn i){var w=await Ws(id);if(w is null)return NotFound();if(await db.Pipelines.AnyAsync(x=>x.WorkspaceId==id)&&(w.Platform!=i.Platform||w.PlatformRef!=i.PlatformRef))return Conflict("platform e platform_ref ficam bloqueados após o primeiro ciclo");w.Name=i.Name;w.Slug=i.Slug;w.SpecsPath=i.SpecsPath;await db.SaveChangesAsync();return Ok(w);}
 [HttpPost("workspaces/{id:guid}/archive")] public async Task<IActionResult> Archive(Guid id){var w=await Ws(id);if(w is null)return NotFound();w.Status="archived";await db.SaveChangesAsync();return Ok(new{w.Id,w.Status});}
 public record AssessmentIn(string Content,string? ClientName);
 [HttpPost("workspaces/{id:guid}/assessments")] public async Task<IActionResult> Assessment(Guid id,AssessmentIn i){var w=await Ws(id);if(w is null)return NotFound();if(!string.IsNullOrWhiteSpace(i.ClientName)){var c=await db.Clients.FirstOrDefaultAsync(x=>x.Name==i.ClientName);if(c is null){c=new Client{Name=i.ClientName};db.Clients.Add(c);}w.Client=c;}var a=await db.Assessments.FirstOrDefaultAsync(x=>x.WorkspaceId==id&&x.Status=="draft")??new Assessment{WorkspaceId=id,ClientId=w.ClientId};a.Content=i.Content;a.UpdatedAt=DateTime.UtcNow;if(a.Id==Guid.Empty)db.Assessments.Add(a);await db.SaveChangesAsync();return Ok(a);}
 [HttpPost("assessments/{id:guid}/complete")] public async Task<IActionResult> Complete(Guid id){var a=await db.Assessments.SingleOrDefaultAsync(x=>x.Id==id&&db.Workspaces.Any(w=>w.Id==x.WorkspaceId&&w.TenantId==Tenant));if(a is null)return NotFound();a.Status="completed";a.UpdatedAt=DateTime.UtcNow;await db.SaveChangesAsync();await analyst.NotifyAsync(Tenant,a.Content,HttpContext.RequestAborted);return Ok(new{a.Id,a.Status});}
 [HttpGet("workspaces/{id:guid}/specs/drafts")] public async Task<IActionResult> Drafts(Guid id){var w=await Ws(id);if(w is null)return NotFound();if(!Directory.Exists(w.SpecsPath))return Ok(Array.Empty<object>());var result=Directory.EnumerateFiles(w.SpecsPath,"*.md",SearchOption.AllDirectories).Select(p=>new{path=p,title=Path.GetFileNameWithoutExtension(p),status=Regex.Match(System.IO.File.ReadAllText(p),@">\s*Status\s*:\s*(\w+)",RegexOptions.IgnoreCase).Groups[1].Value.ToLower()}).Where(x=>x.status=="draft"||x.status=="").ToList();return Ok(result);}
 public record UploadRequest(string Path,string Title,string UserStory,string Criteria,string Wbs);
 [HttpPost("workspaces/{id:guid}/specs/{specId:guid}/upload")] public async Task<IActionResult> Upload(Guid id,Guid specId,UploadRequest i){var w=await Ws(id);var s=await db.Specs.SingleOrDefaultAsync(x=>x.Id==specId&&x.WorkspaceId==id);if(w is null||s is null)return NotFound();var tx=await db.Database.BeginTransactionAsync();IssueResult? issue=null;try{issue=await issues.CreateAsync(i.Title,$"{i.UserStory}\n\n## Critérios\n{i.Criteria}\n\n## WBS\n{i.Wbs}",HttpContext.RequestAborted);var p=new PipelineInstance{WorkspaceId=id,SpecId=specId,ExternalRef=issue.Id};db.Pipelines.Add(p);db.PhaseTransitions.Add(new PhaseTransition{PipelineInstanceId=p.Id,Fase="genese",SourceEvent="upload:"+issue.Id});await db.SaveChangesAsync();await tx.CommitAsync();return Ok(new{pipelineId=p.Id,issueUrl=issue.Url});}catch{await tx.RollbackAsync();if(issue is not null)await issues.DeleteAsync(issue.Id,HttpContext.RequestAborted);throw;}}
 public record CredentialIn(string Perfil,string PlatformUsername,string Scopes,string Token);
 [HttpPost("workspaces/{id:guid}/credentials")] public async Task<IActionResult> Credential(Guid id,CredentialIn i){if(await Ws(id) is null)return NotFound();var c=await db.Credentials.SingleOrDefaultAsync(x=>x.WorkspaceId==id&&x.Perfil==i.Perfil);var reference=await secrets.PutAsync(id.ToString(),i.Perfil,i.Token,HttpContext.RequestAborted);if(c is null){c=new PerfilCredential{WorkspaceId=id,Perfil=i.Perfil};db.Credentials.Add(c);}c.PlatformUsername=i.PlatformUsername;c.Scopes=i.Scopes;c.SecretRef=reference;c.RotatedAt=c.Id==Guid.Empty?null:DateTime.UtcNow;await db.SaveChangesAsync();return Ok(new{c.Id,c.WorkspaceId,c.Perfil,c.PlatformUsername,c.SecretRef,c.Scopes,c.Status,c.CreatedAt,c.RotatedAt});}
 public record Event(Guid PipelineId,string Fase,string SourceEvent,DateTime? EnteredAt);
 [HttpPost("webhooks/phases")] public Task<IActionResult> Webhook(Event e)=>Transition(e);
 [HttpPost("pipelines/reconcile")] public Task<IActionResult> Reconcile(Event e)=>Transition(e);
 async Task<IActionResult> Transition(Event e){if(!await db.Pipelines.AnyAsync(x=>x.Id==e.PipelineId&&db.Workspaces.Any(w=>w.Id==x.WorkspaceId&&w.TenantId==Tenant)))return NotFound();if(await db.PhaseTransitions.AnyAsync(x=>x.PipelineInstanceId==e.PipelineId&&x.SourceEvent==e.SourceEvent))return Ok(new{duplicate=true});var p=await db.Pipelines.FindAsync(e.PipelineId);p!.FaseAtual=e.Fase;db.PhaseTransitions.Add(new PhaseTransition{PipelineInstanceId=e.PipelineId,Fase=e.Fase,SourceEvent=e.SourceEvent,EnteredAt=e.EnteredAt??DateTime.UtcNow});await db.SaveChangesAsync();return Ok(new{duplicate=false});}
}
