namespace SDLC.Dashboard;
public enum WorkspaceStatus{Active,Archived} public enum AssessmentStatus{InProgress,Completed} public enum SpecStatus{Draft,Proposal,Implemented} public enum GateStatus{Pending,Approved,AutoTimeout} public enum CredentialStatus{Active,Revoked,Pending}
public static class Domain { public static readonly string[] Phases={"Requisitos","Design","Dev","Code Review","QA","Segurança","Deploy"}; public const string AssessmentTemplate="## Linha de negócio do cliente\n\n\n## Stack utilizada\n\n\n## Arquiteturas presentes\n\n\n## Constraints de segurança\n\n\n## Observações adicionais\n"; }
public class Client{public Guid Id{get;set;}=Guid.NewGuid();public string Name{get;set;}="";public DateTimeOffset CreatedAt{get;set;}=DateTimeOffset.UtcNow;public List<Workspace> Workspaces{get;set;}=[];}
public class Workspace{public Guid Id{get;set;}=Guid.NewGuid();public string TenantId{get;set;}="default";public Guid? ClientId{get;set;}public Client? Client{get;set;}public string Name{get;set;}="";public string Slug{get;set;}="";public string Platform{get;set;}="github";public string PlatformRef{get;set;}="";public string SpecsPath{get;set;}="specs/";public WorkspaceStatus Status{get;set;}=WorkspaceStatus.Active;public DateTimeOffset CreatedAt{get;set;}=DateTimeOffset.UtcNow;}
public class Assessment{public Guid Id{get;set;}=Guid.NewGuid();public Guid WorkspaceId{get;set;}public Guid ClientId{get;set;}public string Content{get;set;}=Domain.AssessmentTemplate;public AssessmentStatus Status{get;set;}=AssessmentStatus.InProgress;public DateTimeOffset CreatedAt{get;set;}=DateTimeOffset.UtcNow;public DateTimeOffset UpdatedAt{get;set;}=DateTimeOffset.UtcNow;}
public class Spec{public Guid Id{get;set;}=Guid.NewGuid();public Guid WorkspaceId{get;set;}public string Path{get;set;}="";public string Title{get;set;}="";public SpecStatus Status{get;set;}=SpecStatus.Draft;public int Version{get;set;}=1;public DateTimeOffset CreatedAt{get;set;}=DateTimeOffset.UtcNow;public DateTimeOffset UpdatedAt{get;set;}=DateTimeOffset.UtcNow;}
public class PipelineInstance{public Guid Id{get;set;}=Guid.NewGuid();public Guid WorkspaceId{get;set;}public Workspace Workspace{get;set;}=null!;public Guid? SpecId{get;set;}public string CurrentPhase{get;set;}=Domain.Phases[0];public GateStatus GateStatus{get;set;}=GateStatus.Approved;public string ExternalRef{get;set;}="";public string? GateApprover{get;set;}public DateTimeOffset CreatedAt{get;set;}=DateTimeOffset.UtcNow;public List<PhaseTransition> Transitions{get;set;}=[];}
public class PhaseTransition{public Guid Id{get;set;}=Guid.NewGuid();public Guid PipelineInstanceId{get;set;}public string Phase{get;set;}="";public DateTimeOffset EnteredAt{get;set;}=DateTimeOffset.UtcNow;public string SourceEvent{get;set;}="";}
public class ProfileCredential{public Guid Id{get;set;}=Guid.NewGuid();public Guid WorkspaceId{get;set;}public string Profile{get;set;}="";public string PlatformUsername{get;set;}="";public string SecretRef{get;set;}="";public string Scopes{get;set;}="";public CredentialStatus Status{get;set;}=CredentialStatus.Pending;public DateTimeOffset CreatedAt{get;set;}=DateTimeOffset.UtcNow;public DateTimeOffset? RotatedAt{get;set;}}
public record WorkspaceInput(string Name,string Slug,string Platform,string PlatformRef,string? SpecsPath,Guid? ClientId);public record AssessmentInput(string ClientName,string Content,bool Completed);public record CredentialInput(string Profile,string PlatformUsername,string Token,string Scopes);public record PhaseEvent(string ExternalRef,string TargetPhase,string SourceEvent,GateStatus GateStatus);
public record IssueRequest(string Title,string Body); public class DashboardDb:Microsoft.EntityFrameworkCore.DbContext{public DashboardDb(Microsoft.EntityFrameworkCore.DbContextOptions<DashboardDb> o):base(o){}public Microsoft.EntityFrameworkCore.DbSet<Client> Clients=>Set<Client>();public Microsoft.EntityFrameworkCore.DbSet<Workspace> Workspaces=>Set<Workspace>();public Microsoft.EntityFrameworkCore.DbSet<Assessment> Assessments=>Set<Assessment>();public Microsoft.EntityFrameworkCore.DbSet<Spec> Specs=>Set<Spec>();public Microsoft.EntityFrameworkCore.DbSet<PipelineInstance> Pipelines=>Set<PipelineInstance>();public Microsoft.EntityFrameworkCore.DbSet<PhaseTransition> Transitions=>Set<PhaseTransition>();public Microsoft.EntityFrameworkCore.DbSet<ProfileCredential> Credentials=>Set<ProfileCredential>();protected override void OnModelCreating(Microsoft.EntityFrameworkCore.ModelBuilder b){b.Entity<ProfileCredential>().HasIndex(x=>new{x.WorkspaceId,x.Profile,x.Status});b.Entity<PipelineInstance>().HasIndex(x=>x.ExternalRef).IsUnique();b.Entity<PipelineInstance>().HasOne(x=>x.Workspace).WithMany().HasForeignKey(x=>x.WorkspaceId).OnDelete(Microsoft.EntityFrameworkCore.DeleteBehavior.Restrict);}}
public interface IPlatformGateway{Task<string> CreateIssueAsync(Workspace workspace,Spec spec);}public class NoopPlatformGateway:IPlatformGateway{public Task<string>CreateIssueAsync(Workspace w,Spec s)=>Task.FromResult($"local-{Guid.NewGuid():N}");}
public interface ISecretStore{Task<string> StoreAsync(Guid workspace,string profile,string token);}public class KubernetesSecretStore:ISecretStore{public Task<string>StoreAsync(Guid w,string p,string token){if(string.IsNullOrWhiteSpace(token))throw new ArgumentException("Token é obrigatório");return Task.FromResult($"sdlc-dashboard-{w:N}/{p}");}}
