using Microsoft.EntityFrameworkCore;
using SDLC.Dashboard;

var builder = WebApplication.CreateBuilder(args);
builder.Services.AddDbContext<DashboardDb>(o => o.UseSqlite("Data Source=data/dashboard.db"));
builder.Services.AddScoped<IPlatformGateway, NoopPlatformGateway>();
builder.Services.AddScoped<ISecretStore, KubernetesSecretStore>();
builder.Services.AddEndpointsApiExplorer(); builder.Services.AddSwaggerGen();
builder.Services.AddCors(o => o.AddDefaultPolicy(p => p.AllowAnyOrigin().AllowAnyHeader().AllowAnyMethod()));
var app = builder.Build();
Directory.CreateDirectory("data"); using (var scope = app.Services.CreateScope()) scope.ServiceProvider.GetRequiredService<DashboardDb>().Database.EnsureCreated();
app.UseCors(); if (app.Environment.IsDevelopment()) { app.UseSwagger(); app.UseSwaggerUI(); }

app.MapGet("/api/clients", async (string? q, DashboardDb db) => Results.Ok(await db.Clients.Where(x => q == null || x.Name.ToLower().Contains(q.ToLower())).OrderBy(x=>x.Name).ToListAsync()));
app.MapGet("/api/workspaces", async (DashboardDb db) => Results.Ok(await db.Workspaces.Where(x=>x.Status==WorkspaceStatus.Active).Include(x=>x.Client).OrderBy(x=>x.Name).ToListAsync()));
app.MapPost("/api/workspaces", async (WorkspaceInput input, DashboardDb db) => { var w=new Workspace { Name=input.Name, Slug=input.Slug, Platform=input.Platform, PlatformRef=input.PlatformRef, SpecsPath=string.IsNullOrWhiteSpace(input.SpecsPath)?"specs/":input.SpecsPath, ClientId=input.ClientId, TenantId="default" }; db.Workspaces.Add(w); await db.SaveChangesAsync(); return Results.Created($"/api/workspaces/{w.Id}",w); });
app.MapPut("/api/workspaces/{id:guid}", async (Guid id, WorkspaceInput input, DashboardDb db) => { var w=await db.Workspaces.FindAsync(id); if(w==null)return Results.NotFound(); if((w.Platform!=input.Platform||w.PlatformRef!=input.PlatformRef)&&await db.Pipelines.AnyAsync(p=>p.WorkspaceId==id)) return Results.Conflict(new {message="platform e platform_ref não podem ser alterados após o primeiro ciclo."}); w.Name=input.Name;w.Slug=input.Slug;w.Platform=input.Platform;w.PlatformRef=input.PlatformRef;w.SpecsPath=input.SpecsPath;w.ClientId=input.ClientId;await db.SaveChangesAsync();return Results.Ok(w); });
app.MapPost("/api/workspaces/{id:guid}/archive", async (Guid id, DashboardDb db) => { var w=await db.Workspaces.FindAsync(id); if(w==null)return Results.NotFound();w.Status=WorkspaceStatus.Archived;await db.SaveChangesAsync();return Results.NoContent(); });
app.MapGet("/api/workspaces/{id:guid}/assessment", async (Guid id, DashboardDb db) => Results.Ok(await db.Assessments.Where(x=>x.WorkspaceId==id).OrderByDescending(x=>x.UpdatedAt).FirstOrDefaultAsync()));
app.MapPut("/api/workspaces/{id:guid}/assessment", async (Guid id, AssessmentInput input, DashboardDb db) => { var w=await db.Workspaces.FindAsync(id);if(w==null)return Results.NotFound(); var c=await db.Clients.FirstOrDefaultAsync(x=>x.Name.ToLower()==input.ClientName.Trim().ToLower());if(c==null){c=new Client{Name=input.ClientName.Trim()};db.Clients.Add(c);await db.SaveChangesAsync();}var a=await db.Assessments.FirstOrDefaultAsync(x=>x.WorkspaceId==id);if(a==null){a=new Assessment{WorkspaceId=id};db.Assessments.Add(a);}a.ClientId=c.Id;a.Content=string.IsNullOrWhiteSpace(input.Content)?Domain.AssessmentTemplate:input.Content;a.Status=input.Completed?AssessmentStatus.Completed:AssessmentStatus.InProgress;a.UpdatedAt=DateTimeOffset.UtcNow;if(input.Completed)w.ClientId=c.Id;await db.SaveChangesAsync();return Results.Ok(a); });
app.MapGet("/api/workspaces/{id:guid}/specs", async (Guid id, DashboardDb db) => Results.Ok(await db.Specs.Where(x=>x.WorkspaceId==id&&x.Status==SpecStatus.Draft).OrderBy(x=>x.Title).ToListAsync()));
app.MapGet("/api/workspaces/{id:guid}/dashboard", async (Guid id, DashboardDb db) => { var phases=Domain.Phases.ToDictionary(x=>x,x=>0);foreach(var g in await db.Pipelines.Where(x=>x.WorkspaceId==id).GroupBy(x=>x.CurrentPhase).Select(x=>new{x.Key,Count=x.Count()}).ToListAsync())phases[g.Key]=g.Count;var pending=await db.Pipelines.Where(x=>x.WorkspaceId==id&&x.GateStatus==GateStatus.Pending).Select(x=>new {x.Id,x.CurrentPhase,x.ExternalRef,x.GateApprover}).ToListAsync();return Results.Ok(new{phases,pending}); });
app.MapPost("/api/workspaces/{id:guid}/specs/{specId:guid}/raise-us", async (Guid id, Guid specId, DashboardDb db, IPlatformGateway platform) => { var s=await db.Specs.SingleOrDefaultAsync(x=>x.Id==specId&&x.WorkspaceId==id&&x.Status==SpecStatus.Draft);if(s==null)return Results.NotFound();var w=await db.Workspaces.FindAsync(id);var issue=await platform.CreateIssueAsync(w!,s);var p=new PipelineInstance{WorkspaceId=id,SpecId=specId,CurrentPhase=Domain.Phases[0],GateStatus=GateStatus.Approved,ExternalRef=issue};p.Transitions.Add(new PhaseTransition{Phase=p.CurrentPhase,SourceEvent="cycle.created"});db.Pipelines.Add(p);await db.SaveChangesAsync();return Results.Created($"/api/pipelines/{p.Id}",p); });
app.MapPost("/api/webhooks/phase", async (PhaseEvent e, DashboardDb db) => { var p=await db.Pipelines.SingleOrDefaultAsync(x=>x.ExternalRef==e.ExternalRef);if(p==null)return Results.NotFound();if(p.CurrentPhase==e.TargetPhase)return Results.Ok(new{changed=false});p.CurrentPhase=e.TargetPhase;p.GateStatus=e.GateStatus;p.Transitions.Add(new PhaseTransition{Phase=e.TargetPhase,SourceEvent=e.SourceEvent});await db.SaveChangesAsync();return Results.Ok(new{changed=true}); });
app.MapPost("/api/workspaces/{id:guid}/credentials", async (Guid id, CredentialInput input, DashboardDb db, ISecretStore secrets) => { foreach(var old in db.Credentials.Where(x=>x.WorkspaceId==id&&x.Profile==input.Profile&&x.Status==CredentialStatus.Active))old.Status=CredentialStatus.Revoked;var reference=await secrets.StoreAsync(id,input.Profile,input.Token);var c=new ProfileCredential{WorkspaceId=id,Profile=input.Profile,PlatformUsername=input.PlatformUsername,SecretRef=reference,Scopes=input.Scopes,Status=CredentialStatus.Active};db.Credentials.Add(c);await db.SaveChangesAsync();return Results.Created($"/api/credentials/{c.Id}",new{c.Id,c.Profile,c.PlatformUsername,c.SecretRef,c.Scopes,c.Status}); });
app.MapGet("/api/workspaces/{id:guid}/credentials", async (Guid id, DashboardDb db) => Results.Ok(await db.Credentials.Where(x=>x.WorkspaceId==id).Select(x=>new{x.Id,x.Profile,x.PlatformUsername,x.SecretRef,x.Scopes,x.Status,x.CreatedAt,x.RotatedAt}).ToListAsync()));
app.Run();
