using System.Net.Http.Json; using System.Text.Json.Serialization;
namespace SdlcDashboard.Api.Infrastructure;
public record IssueResult(string Id,string Url);
public interface IIssueProvider { Task<IssueResult> CreateAsync(string title,string body,CancellationToken ct); Task DeleteAsync(string id,CancellationToken ct); }
public sealed class GitHubIssueProvider(IHttpClientFactory factory,IConfiguration config):IIssueProvider { public async Task<IssueResult> CreateAsync(string title,string body,CancellationToken ct){ var owner=config["GitHub:Owner"]; var repo=config["GitHub:Repo"]; if(string.IsNullOrWhiteSpace(owner)||string.IsNullOrWhiteSpace(repo)) throw new InvalidOperationException("GitHub:Owner e GitHub:Repo obrigatorios"); var c=factory.CreateClient("github"); var r=await c.PostAsJsonAsync($"repos/{owner}/{repo}/issues",new {title,body},ct); r.EnsureSuccessStatusCode(); var x=await r.Content.ReadFromJsonAsync<GhIssue>(cancellationToken:ct)??throw new InvalidOperationException("Resposta GitHub vazia"); return new(x.Number.ToString(),x.HtmlUrl); } public async Task DeleteAsync(string id,CancellationToken ct){ var o=config["GitHub:Owner"];var r=config["GitHub:Repo"];if(o is null||r is null)return; await factory.CreateClient("github").DeleteAsync($"repos/{o}/{r}/issues/{id}",ct); } private record GhIssue([property:JsonPropertyName("number")]int Number,[property:JsonPropertyName("html_url")]string HtmlUrl); }
public interface ISecretStore { Task<string> PutAsync(string workspace,string perfil,string token,CancellationToken ct); }
public sealed class KubernetesSecretStore(IConfiguration config):ISecretStore { public async Task<string> PutAsync(string workspace,string perfil,string token,CancellationToken ct){ var reference=$"{config["Kubernetes:Namespace"]??"default"}/sdlc-{workspace}-{perfil}"; var endpoint=config["Kubernetes:ApiUrl"]; if(!string.IsNullOrWhiteSpace(endpoint)){ using var http=new HttpClient(); var response=await http.PostAsJsonAsync(endpoint,new {name=reference,token},ct); response.EnsureSuccessStatusCode(); } return reference; } }
public interface IAnalystClient { Task NotifyAsync(string tenant,string content,CancellationToken ct); }
public sealed class AnalystClient(IHttpClientFactory f,IConfiguration c):IAnalystClient { public async Task NotifyAsync(string tenant,string content,CancellationToken ct){ var url=c["Analyst:ApiUrl"]; if(string.IsNullOrWhiteSpace(url))return; var r=await f.CreateClient("analyst").PostAsJsonAsync("assessments",new {tenantId=tenant,content},ct); r.EnsureSuccessStatusCode(); } }
