namespace Backend.Persistence.Domain;
public enum WorkspacePlatform { Github, AzureDevOps } public enum WorkspaceStatus { Active, Archived } public enum AssessmentStatus { EmAndamento, Concluido } public enum PipelinePhase { Requisitos, Design, Dev, CodeReview, Qa, Seguranca, Deploy } public enum GateStatus { Pending, Approved, AutoTimeout } public enum Perfil { AnalistaRequisitos, Arquiteto, Dev, Revisor, Qa, Seguranca, ReleaseDeploy } public enum CredentialStatus { Active, Revoked, Pending }
public sealed class Client { public long Id {get;set;} public required string Name {get;set;} public DateTime CreatedAt {get;set;} public ICollection<Workspace> Workspaces {get;}=new List<Workspace>(); public ICollection<Assessment> Assessments {get;}=new List<Assessment>(); }
public sealed class Workspace { public long Id {get;set;} public string? TenantId {get;set;} public long? ClientId {get;set;} public required string Name {get;set;} public required string Slug {get;set;} public WorkspacePlatform Platform {get;set;} public required string PlatformRef {get;set;} public string SpecsPath {get;set;}="specs/"; public string? SpecsRepo {get;set;} public string? CodeRepo {get;set;} public string? AdoWorkItemType {get;set;} public string? AppSecretRef {get;set;} public WorkspaceStatus Status {get;set;}=WorkspaceStatus.Active; public DateTime CreatedAt {get;set;} public Client? Client {get;set;} public ICollection<Assessment> Assessments {get;}=new List<Assessment>(); public ICollection<Spec> Specs {get;}=new List<Spec>(); public ICollection<PipelineInstance> PipelineInstances {get;}=new List<PipelineInstance>(); public ICollection<PerfilCredential> PerfilCredentials {get;}=new List<PerfilCredential>(); }
public sealed class Assessment { public long Id {get;set;} public long WorkspaceId {get;set;} public long ClientId {get;set;} public required string Content {get;set;} public string? FigmaProjectUrl {get;set;} public long? SelectedDesignSystemProposalId {get;set;} public AssessmentStatus Status {get;set;}=AssessmentStatus.EmAndamento; public DateTime CreatedAt {get;set;} public DateTime UpdatedAt {get;set;} public Workspace? Workspace {get;set;} public Client? Client {get;set;} public DesignSystemProposal? SelectedDesignSystemProposal {get;set;} }
public sealed class Spec { public long Id {get;set;} public long WorkspaceId {get;set;} public required string Path {get;set;} public required string Title {get;set;} public required string Status {get;set;} public int Version {get;set;} public DateTime CreatedAt {get;set;} public DateTime UpdatedAt {get;set;} public Workspace? Workspace {get;set;} public ICollection<PipelineInstance> PipelineInstances {get;}=new List<PipelineInstance>(); }
public sealed class PipelineInstance { public long Id {get;set;} public long WorkspaceId {get;set;} public long? SpecId {get;set;} public PipelinePhase FaseAtual {get;set;}=PipelinePhase.Requisitos; public GateStatus GateStatus {get;set;}=GateStatus.Approved; public required string ExternalRef {get;set;} public string? PrRef {get;set;} public DateTime CreatedAt {get;set;} public Workspace? Workspace {get;set;} public Spec? Spec {get;set;} public ICollection<PhaseTransition> PhaseTransitions {get;}=new List<PhaseTransition>(); public UxGateDecision? UxGateDecision {get;set;} }
public sealed class PhaseTransition { public long Id {get;set;} public long PipelineInstanceId {get;set;} public PipelinePhase Fase {get;set;} public DateTime EnteredAt {get;set;} public required string SourceEvent {get;set;} public string? DeliveryId {get;set;} public PipelineInstance? PipelineInstance {get;set;} }
public sealed class PerfilCredential { public long Id {get;set;} public long WorkspaceId {get;set;} public Perfil Perfil {get;set;} public required string PlatformUsername {get;set;} public required string SecretRef {get;set;} public string? Scopes {get;set;} public CredentialStatus Status {get;set;}=CredentialStatus.Pending; public DateTime CreatedAt {get;set;} public DateTime? RotatedAt {get;set;} public Workspace? Workspace {get;set;} }
// Recorded by SpecUsEndpoints.Handle *before* the local PipelineInstance row is guaranteed to exist -
// the durable, backend-only proof that ReconciliationPollerService relies on (seção 6.2, Security
// review on PR #17) instead of trusting anything readable/writable by a GitHub collaborator (label,
// Issue body). Only the "Subir US" session-authenticated flow can ever create a row here.
public sealed class SpecPublication { public long Id {get;set;} public long WorkspaceId {get;set;} public long? SpecId {get;set;} public required string ExternalRef {get;set;} public DateTime CreatedAt {get;set;} public Workspace? Workspace {get;set;} }
// Gate de UX (spec gate-ux-figma.md secao 3): a sugestao do Analista (tem_tarefas_design/justificativa,
// campos opcionais no mesmo JSON de dor_atendido) e a confirmacao/sobrescrita humana ficam aqui, 1:1 com
// a PipelineInstance que a sugestao acompanhou. Nao bloqueia a fase Requisitos (GateStatus da
// PipelineInstance) - e so um metadado informativo ate ser confirmado.
public sealed class UxGateDecision { public long Id {get;set;} public long PipelineInstanceId {get;set;} public bool? TemTarefasDesign {get;set;} public string? JustificativaDesign {get;set;} public bool Confirmado {get;set;} public string? MotivoSobrescrita {get;set;} public string? DecididoPor {get;set;} public DateTime? DecididoEm {get;set;} public DateTime CreatedAt {get;set;} public PipelineInstance? PipelineInstance {get;set;} public ICollection<UxMockup> Mockups {get;}=new List<UxMockup>(); }
// Um SVG por tela (spec seção 5), gerado pelo perfil Hermes `ux` e guardado como blob - BlobPath aponta
// para IBlobStore, o conteudo em si nao fica na linha do banco (mesmo padrão de specs/assessments).
public sealed class UxMockup { public long Id {get;set;} public long UxGateDecisionId {get;set;} public required string Nome {get;set;} public required string BlobPath {get;set;} public DateTime CreatedAt {get;set;} public UxGateDecision? UxGateDecision {get;set;} }
// Uma das 3 alternativas de design system propostas por rodada (spec seção 4.2) - vinculada ao Workspace
// (recurso do cliente, reaproveitado por todas as specs dali), nao a uma spec/PipelineInstance especifica.
public sealed class DesignSystemProposal { public long Id {get;set;} public long WorkspaceId {get;set;} public required string Nome {get;set;} public required string PaletaJson {get;set;} public required string Tipografia {get;set;} public required string Estilo {get;set;} public required string Justificativa {get;set;} public bool Selecionado {get;set;} public string? SelecionadoPor {get;set;} public DateTime? SelecionadoEm {get;set;} public DateTime CreatedAt {get;set;} public Workspace? Workspace {get;set;} }
