namespace Backend.Persistence.Domain;
public enum WorkspacePlatform { Github, AzureDevOps } public enum WorkspaceStatus { Active, Archived } public enum AssessmentStatus { EmAndamento, Concluido } public enum PipelinePhase { Requisitos, Design, Dev, CodeReview, Qa, Seguranca, Deploy } public enum GateStatus { Pending, Approved, AutoTimeout } public enum Perfil { AnalistaRequisitos, Arquiteto, Dev, Revisor, Qa, Seguranca, ReleaseDeploy } public enum CredentialStatus { Active, Revoked, Pending }
public sealed class Client { public long Id {get;set;} public required string Name {get;set;} public DateTime CreatedAt {get;set;} public ICollection<Workspace> Workspaces {get;}=new List<Workspace>(); public ICollection<Assessment> Assessments {get;}=new List<Assessment>(); }
public sealed class Workspace { public long Id {get;set;} public string? TenantId {get;set;} public long? ClientId {get;set;} public required string Name {get;set;} public required string Slug {get;set;} public WorkspacePlatform Platform {get;set;} public required string PlatformRef {get;set;} public string SpecsPath {get;set;}="specs/"; public string? SpecsRepo {get;set;} public string? CodeRepo {get;set;} public string? AdoWorkItemType {get;set;} public string? AppSecretRef {get;set;} public WorkspaceStatus Status {get;set;}=WorkspaceStatus.Active; public DateTime CreatedAt {get;set;} public Client? Client {get;set;} public ICollection<Assessment> Assessments {get;}=new List<Assessment>(); public ICollection<Spec> Specs {get;}=new List<Spec>(); public ICollection<PipelineInstance> PipelineInstances {get;}=new List<PipelineInstance>(); public ICollection<PerfilCredential> PerfilCredentials {get;}=new List<PerfilCredential>(); }
public sealed class Assessment { public long Id {get;set;} public long WorkspaceId {get;set;} public long ClientId {get;set;} public required string Content {get;set;} public AssessmentStatus Status {get;set;}=AssessmentStatus.EmAndamento; public DateTime CreatedAt {get;set;} public DateTime UpdatedAt {get;set;} public Workspace? Workspace {get;set;} public Client? Client {get;set;} }
public sealed class Spec { public long Id {get;set;} public long WorkspaceId {get;set;} public required string Path {get;set;} public required string Title {get;set;} public required string Status {get;set;} public int Version {get;set;} public DateTime CreatedAt {get;set;} public DateTime UpdatedAt {get;set;} public Workspace? Workspace {get;set;} public ICollection<PipelineInstance> PipelineInstances {get;}=new List<PipelineInstance>(); }
public sealed class PipelineInstance { public long Id {get;set;} public long WorkspaceId {get;set;} public long? SpecId {get;set;} public PipelinePhase FaseAtual {get;set;}=PipelinePhase.Requisitos; public GateStatus GateStatus {get;set;}=GateStatus.Approved; public required string ExternalRef {get;set;} public string? PrRef {get;set;} public DateTime CreatedAt {get;set;} public Workspace? Workspace {get;set;} public Spec? Spec {get;set;} public ICollection<PhaseTransition> PhaseTransitions {get;}=new List<PhaseTransition>(); }
public sealed class PhaseTransition { public long Id {get;set;} public long PipelineInstanceId {get;set;} public PipelinePhase Fase {get;set;} public DateTime EnteredAt {get;set;} public required string SourceEvent {get;set;} public string? DeliveryId {get;set;} public PipelineInstance? PipelineInstance {get;set;} }
public sealed class PerfilCredential { public long Id {get;set;} public long WorkspaceId {get;set;} public Perfil Perfil {get;set;} public required string PlatformUsername {get;set;} public required string SecretRef {get;set;} public string? Scopes {get;set;} public CredentialStatus Status {get;set;}=CredentialStatus.Pending; public DateTime CreatedAt {get;set;} public DateTime? RotatedAt {get;set;} public Workspace? Workspace {get;set;} }
