using Backend.Persistence.Data;
using Backend.Persistence.Domain;
using Microsoft.EntityFrameworkCore;
using System.Text.Json.Serialization;
namespace Backend.Api.Apis;
public static class WorkspaceEndpoints
{
 public static IEndpointRouteBuilder MapWorkspaceEndpoints(this IEndpointRouteBuilder e){e.MapPost("/workspaces",Create);e.MapPatch("/workspaces/{id:long}",Update);e.MapPost("/workspaces/{id:long}/archive",Archive);return e;}
 static async Task<IResult> Create(CreateWorkspaceRequest r,AppDbContext db,CancellationToken ct){var er=Validate(r.Name,r.Platform,r.PlatformRef);if(er.Count>0)return Results.UnprocessableEntity(new{errors=er});var w=new Workspace{Name=r.Name!.Trim(),Slug=Slug(r.Name),Platform=Parse(r.Platform!)!.Value,PlatformRef=r.PlatformRef!.Trim(),ClientId=r.ClientId,CreatedAt=DateTime.UtcNow};if(r.SpecsPath is not null)w.SpecsPath=r.SpecsPath.Trim();w.SpecsRepo=r.SpecsRepo;w.CodeRepo=r.CodeRepo;w.AdoWorkItemType=r.AdoWorkItemType;w.AppSecretRef=r.AppSecretRef;if(await db.Workspaces.AnyAsync(x=>x.Slug==w.Slug,ct))return Results.UnprocessableEntity(new{errors=new[]{"name: workspace slug already exists"}});if(w.ClientId is not null&&!await db.Clients.AnyAsync(x=>x.Id==w.ClientId,ct))return Results.UnprocessableEntity(new{errors=new[]{"client_id: client does not exist"}});db.Workspaces.Add(w);await db.SaveChangesAsync(ct);return Results.Created($"/workspaces/{w.Id}",Response(w));}
 static async Task<IResult> Update(long id,UpdateWorkspaceRequest r,AppDbContext db,CancellationToken ct){var w=await db.Workspaces.SingleOrDefaultAsync(x=>x.Id==id,ct);if(w is null)return Results.NotFound();var p=r.Platform is null?w.Platform:Parse(r.Platform);if(r.Platform is not null&&p is null)return Results.UnprocessableEntity(new{errors=new[]{"platform: must be github or azure_devops"}});if(r.PlatformRef is not null&&string.IsNullOrWhiteSpace(r.PlatformRef))return Results.UnprocessableEntity(new{errors=new[]{"platform_ref: is required"}});if((p!=w.Platform||(r.PlatformRef is not null&&r.PlatformRef.Trim()!=w.PlatformRef))&&await db.PipelineInstances.AnyAsync(x=>x.WorkspaceId==id,ct))return Results.Conflict(new{error="platform and platform_ref cannot be changed after a pipeline_instance is linked to the workspace"});if(r.Name is not null&&string.IsNullOrWhiteSpace(r.Name))return Results.UnprocessableEntity(new{errors=new[]{"name: is required"}});if(r.Name is not null){w.Name=r.Name.Trim();w.Slug=Slug(r.Name);}if(p is not null)w.Platform=p.Value;if(r.PlatformRef is not null)w.PlatformRef=r.PlatformRef.Trim();if(r.ClientId.HasValue)w.ClientId=r.ClientId;if(r.SpecsPath is not null)w.SpecsPath=r.SpecsPath.Trim();if(r.SpecsRepo is not null)w.SpecsRepo=r.SpecsRepo;if(r.CodeRepo is not null)w.CodeRepo=r.CodeRepo;if(r.AdoWorkItemType is not null)w.AdoWorkItemType=r.AdoWorkItemType;if(r.AppSecretRef is not null)w.AppSecretRef=r.AppSecretRef;if(await db.Workspaces.AnyAsync(x=>x.Id!=id&&x.Slug==w.Slug,ct))return Results.UnprocessableEntity(new{errors=new[]{"name: workspace slug already exists"}});await db.SaveChangesAsync(ct);return Results.Ok(Response(w));}
 static async Task<IResult> Archive(long id,AppDbContext db,CancellationToken ct){var w=await db.Workspaces.SingleOrDefaultAsync(x=>x.Id==id,ct);if(w is null)return Results.NotFound();w.Status=WorkspaceStatus.Archived;await db.SaveChangesAsync(ct);return Results.Ok(Response(w));}
 static List<string> Validate(string? n,string? p,string? r){var e=new List<string>();if(string.IsNullOrWhiteSpace(n))e.Add("name: is required");if(Parse(p) is null)e.Add("platform: must be github or azure_devops");if(string.IsNullOrWhiteSpace(r))e.Add("platform_ref: is required");return e;}
 static WorkspacePlatform? Parse(string? p)=>p?.ToLowerInvariant() switch{"github"=>WorkspacePlatform.Github,"azure_devops"=>WorkspacePlatform.AzureDevOps,_=>null};static string Slug(string n)=>string.Join('-',n.Trim().ToLowerInvariant().Split(' ',StringSplitOptions.RemoveEmptyEntries)).Replace("/","-");static WorkspaceResponse Response(Workspace w)=>new(w.Id,w.Name,w.Slug,w.Platform==WorkspacePlatform.Github?"github":"azure_devops",w.PlatformRef,w.ClientId,w.Status==WorkspaceStatus.Active?"active":"archived",w.CreatedAt);
}
public sealed record CreateWorkspaceRequest([property:JsonPropertyName("name")]string? Name,[property:JsonPropertyName("platform")]string? Platform,[property:JsonPropertyName("platform_ref")]string? PlatformRef,[property:JsonPropertyName("client_id")]long? ClientId=null,[property:JsonPropertyName("specs_path")]string? SpecsPath=null,[property:JsonPropertyName("specs_repo")]string? SpecsRepo=null,[property:JsonPropertyName("code_repo")]string? CodeRepo=null,[property:JsonPropertyName("ado_work_item_type")]string? AdoWorkItemType=null,[property:JsonPropertyName("app_secret_ref")]string? AppSecretRef=null);
public sealed record UpdateWorkspaceRequest([property:JsonPropertyName("name")]string? Name=null,[property:JsonPropertyName("platform")]string? Platform=null,[property:JsonPropertyName("platform_ref")]string? PlatformRef=null,[property:JsonPropertyName("client_id")]long? ClientId=null,[property:JsonPropertyName("specs_path")]string? SpecsPath=null,[property:JsonPropertyName("specs_repo")]string? SpecsRepo=null,[property:JsonPropertyName("code_repo")]string? CodeRepo=null,[property:JsonPropertyName("ado_work_item_type")]string? AdoWorkItemType=null,[property:JsonPropertyName("app_secret_ref")]string? AppSecretRef=null);
public sealed record WorkspaceResponse(long Id,string Name,string Slug,string Platform,string PlatformRef,long? ClientId,string Status,DateTime CreatedAt);
