// <auto-generated />
using System;
using Backend.Persistence.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Backend.Persistence.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.8");

            modelBuilder.Entity("Backend.Persistence.Domain.Assessment", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long>("ClientId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<long>("WorkspaceId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ClientId");

                    b.HasIndex("WorkspaceId");

                    b.ToTable("assessment", (string)null);
                });

            modelBuilder.Entity("Backend.Persistence.Domain.Client", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Name");

                    b.ToTable("client", (string)null);
                });

            modelBuilder.Entity("Backend.Persistence.Domain.PerfilCredential", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("Perfil")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PlatformUsername")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("RotatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Scopes")
                        .HasColumnType("TEXT");

                    b.Property<string>("SecretRef")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<long>("WorkspaceId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("WorkspaceId", "Perfil")
                        .IsUnique()
                        .HasDatabaseName("IX_perfil_credential_active_per_perfil")
                        .HasFilter("status = 0");

                    b.HasIndex("WorkspaceId", "Perfil", "Status");

                    b.ToTable("perfil_credential", (string)null);
                });

            modelBuilder.Entity("Backend.Persistence.Domain.PhaseTransition", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("EnteredAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("Fase")
                        .HasColumnType("INTEGER");

                    b.Property<long>("PipelineInstanceId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SourceEvent")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("PipelineInstanceId");

                    b.ToTable("phase_transition", (string)null);
                });

            modelBuilder.Entity("Backend.Persistence.Domain.PipelineInstance", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("ExternalRef")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("FaseAtual")
                        .HasColumnType("INTEGER");

                    b.Property<int>("GateStatus")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PrRef")
                        .HasColumnType("TEXT");

                    b.Property<long?>("SpecId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("WorkspaceId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("SpecId");

                    b.HasIndex("WorkspaceId", "ExternalRef")
                        .IsUnique();

                    b.ToTable("pipeline_instance", (string)null);
                });

            modelBuilder.Entity("Backend.Persistence.Domain.Spec", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("Version")
                        .HasColumnType("INTEGER");

                    b.Property<long>("WorkspaceId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("WorkspaceId", "Path")
                        .IsUnique();

                    b.ToTable("spec", (string)null);
                });

            modelBuilder.Entity("Backend.Persistence.Domain.Workspace", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AdoWorkItemType")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue("User Story");

                    b.Property<string>("AppSecretRef")
                        .HasColumnType("TEXT");

                    b.Property<long?>("ClientId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CodeRepo")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Platform")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PlatformRef")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SpecsPath")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue("specs/");

                    b.Property<string>("SpecsRepo")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TenantId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue("default");

                    b.HasKey("Id");

                    b.HasIndex("ClientId");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("workspace", null, t =>
                        {
                            t.HasCheckConstraint("CK_workspace_platform", "platform IN (0,1)");

                            t.HasCheckConstraint("CK_workspace_status", "status IN (0,1)");
                        });
                });

            modelBuilder.Entity("Backend.Persistence.Domain.Assessment", b =>
                {
                    b.HasOne("Backend.Persistence.Domain.Client", "Client")
                        .WithMany("Assessments")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Backend.Persistence.Domain.Workspace", "Workspace")
                        .WithMany("Assessments")
                        .HasForeignKey("WorkspaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Client");

                    b.Navigation("Workspace");
                });

            modelBuilder.Entity("Backend.Persistence.Domain.PerfilCredential", b =>
                {
                    b.HasOne("Backend.Persistence.Domain.Workspace", "Workspace")
                        .WithMany("PerfilCredentials")
                        .HasForeignKey("WorkspaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Workspace");
                });

            modelBuilder.Entity("Backend.Persistence.Domain.PhaseTransition", b =>
                {
                    b.HasOne("Backend.Persistence.Domain.PipelineInstance", "PipelineInstance")
                        .WithMany("PhaseTransitions")
                        .HasForeignKey("PipelineInstanceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PipelineInstance");
                });

            modelBuilder.Entity("Backend.Persistence.Domain.PipelineInstance", b =>
                {
                    b.HasOne("Backend.Persistence.Domain.Spec", "Spec")
                        .WithMany("PipelineInstances")
                        .HasForeignKey("SpecId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Backend.Persistence.Domain.Workspace", "Workspace")
                        .WithMany("PipelineInstances")
                        .HasForeignKey("WorkspaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Spec");

                    b.Navigation("Workspace");
                });

            modelBuilder.Entity("Backend.Persistence.Domain.Spec", b =>
                {
                    b.HasOne("Backend.Persistence.Domain.Workspace", "Workspace")
                        .WithMany("Specs")
                        .HasForeignKey("WorkspaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Workspace");
                });

            modelBuilder.Entity("Backend.Persistence.Domain.Workspace", b =>
                {
                    b.HasOne("Backend.Persistence.Domain.Client", "Client")
                        .WithMany("Workspaces")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Client");
                });

            modelBuilder.Entity("Backend.Persistence.Domain.Client", b =>
                {
                    b.Navigation("Assessments");

                    b.Navigation("Workspaces");
                });

            modelBuilder.Entity("Backend.Persistence.Domain.PipelineInstance", b =>
                {
                    b.Navigation("PhaseTransitions");
                });

            modelBuilder.Entity("Backend.Persistence.Domain.Spec", b =>
                {
                    b.Navigation("PipelineInstances");
                });

            modelBuilder.Entity("Backend.Persistence.Domain.Workspace", b =>
                {
                    b.Navigation("Assessments");

                    b.Navigation("PerfilCredentials");

                    b.Navigation("PipelineInstances");

                    b.Navigation("Specs");
                });
#pragma warning restore 612, 618
        }
    }
}
